admin/src/web/__init__.py
from flask import Flask
from flask import render_template

from src.core import database
from src.core import seeds
from src.web.config import config 
from src.web.helpers import handlers
from src.web.controllers.issues import issue_blueprint #importo controller de issues para registrarlo
from src.web.controllers.auth import auth_blueprint

def create_app(env="development", static_folder="static"): #funcion que crea mi app 
    app = Flask(__name__, static_folder=static_folder)

    app.config.from_object(config[env])

    database.init_app(app) #ejecuto el metodo init_app y le mando mi app flask


    @app.get("/") #decorador, se ejecuta cuando se hace un get al / de mi app 
    def home(): 
        contenido = "mundo"
        return render_template("home.html", contenido=contenido)
    
    #Reigstro controller de issues
    app.register_blueprint(issue_blueprint)
    #registro controller de auth 
    app.register_blueprint(auth_blueprint)

    app.register_error_handler(404, handlers.not_found_error) #cuando encuentre un 404 ejecutar la funcion
    app.register_error_handler(500, handlers.internal_server_error)
    
    @app.cli.command(name="resetdb")
    def resetdb():
        database.reset_db()
        
    @app.cli.command(name="seeds")
    def seedsdb():
        seeds.run()

    return app

admin/src/web/controllers/auth.py
from flask import Blueprint
from flask import render_template

auth_blueprint = Blueprint("auth", __name__, url_prefix="/auth")

@auth_blueprint.get("/")
def login():
    return render_template("auth/login.html")

@auth_blueprint.post("/authenticate")
def authenticate():
    pass

@auth_blueprint.get("/logout")
def logout():
    pass

admin/src/web/controllers/issues.py
#controllers de issue
from flask import Blueprint
from flask import render_template
from src.core import board

issue_blueprint = Blueprint("issues", __name__, url_prefix="/consultas")

@issue_blueprint.get("/")
def issue_index():

    issues = board.list_issues() #obtengo los issues del modelo 
    
    return render_template("issues/index.html", issues=issues) 
    
    #toma este archivo y se lo manda al template 
    #combina vista con modelo y se lo retorna al browser 

admin/src/web/templates/error.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='error.css') }}" />
    {% endblock %}
    <title>Error!</title>
  </head>
  <body>
    <h1>{{ error_name }}</h1>
    <p class="zoom-area"><b>Error!</b> {{ error_description }} </p>
      <div class="link-container">
        <a href="{{ url_for('home') }}" class="more-link">Go to the homepage</a>
      </div>
  </body>
</html>

admin/src/web/templates/home.html
{% extends "layout.html" %} <!--heredo del layout-->
{% block title %}Ejemplo Proyecto{% endblock %}
{% block head %}
  {{ super() }} <!--toma la cabecera del padre (layout)-->
{% endblock %}
{% block content %} <!-- redefino -->
        {% if contenido == "Argentina" %}
            <h1>La Ciudad Autonónoma de Buenos Aires es la capital de {{contenido}} <h1>
        {% else %}
            <h1>Inicio {{contenido}}<h1>
        {% endif %}
        <a href="{{url_for('issues.issue_index')}}"> Issues </a>
{% endblock %}

admin/src/web/templates/issues/index.html
{% extends "layout.html" %}
{% block title %}Consultas{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
  <h1>Consultas</h1>

  <table class="index-table box">
    <thead>
      <tr>
        <th>#</th>
        <th>Email</th>
        <th>Título</th>
        <th>Descripción</th>
        <th>Estado</th>
        <th>Creado en</th>
      </tr>
    </thead>
    <tbody>
      {% for issue in issues %}
      <tr>
        <th>{{ issue.id }}</th>
        <th>{{ issue.email }}</th>
        <th>{{ issue.title }}</th>
        <th>{{ issue.description }}</th>
        <th>{{ issue.status }}</th>
        <th>{{ issue.inserted_at }}</th>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

admin/src/web/templates/layout.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% block head %} <!--bloque de head-->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    <title>{% block title %}{% endblock %}</title> <!--bloque de titulos-->
    {% endblock %}
  </head>
  <body>
    <div id="navbar">
      {% block navbar %} <!--bloque de navegacion-->
      {% endblock %}
    </div>
    <div id="main">
      {% block content %} <!--bloque de contenido principal-->
      {% endblock %}
    </div>
    <div id="footer"> <!--bloque de footer-->
      {% block footer %}
      {% endblock %}
    </div>
  </body>
</html>